spring:
  application:
    name: order-service
  datasource:
    username: sa
    password: 1234$
    url: jdbc:sqlserver://localhost\ADMIN:1433;database=QUANLYNHANSU;encrypt=true;trustServerCertificate=true;

  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect. org.hibernate.dialect.SQLServer2008Dialect
